/*
 * Copyright 2023-2024 NXP
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Includes */

#include "fsl_fract_pll.h"
#include "fsl_ccm.h"
#include "fsl_clock.h"
#include "fsl_power.h"
#include "fsl_src.h"
#include "fsl_device_registers.h"

/* Local Defines */

/* Local Types */

/* Local Functions */

static bool CLOCK_SourcePdIsOn(uint32_t sourceIdx);

/* Local Variables */

uint64_t g_clockExt1Rate = 0UL;

const pll_attr_t g_pllAttrs[CLOCK_NUM_PLL] =
{
    [CLOCK_PLL_SYS1].isFrac = true,
    [CLOCK_PLL_SYS1].numDFS = 3U,

    [CLOCK_PLL_AUDIO1].isFrac = true,
    [CLOCK_PLL_AUDIO1].numDFS = 0U,

    [CLOCK_PLL_AUDIO2].isFrac = true,
    [CLOCK_PLL_AUDIO2].numDFS = 0U,

    [CLOCK_PLL_ENCODER].isFrac = false,
    [CLOCK_PLL_ENCODER].numDFS = 2U,

    [CLOCK_PLL_ARM].isFrac = false,
    [CLOCK_PLL_ARM].numDFS = 4U,

    [CLOCK_PLL_DRAM].isFrac = true,
    [CLOCK_PLL_DRAM].numDFS = 0U,

    [CLOCK_PLL_HSIO].isFrac = true,
    [CLOCK_PLL_HSIO].numDFS = 0U,

    [CLOCK_PLL_LDB].isFrac = true,
    [CLOCK_PLL_LDB].numDFS = 0U,
};

/* TODO below array need to be updated when clock tree info is ready */
const uint8_t g_clockRootMux[CLOCK_NUM_ROOT][CLOCK_NUM_ROOT_MUX_SEL] =
{
    [CLOCK_ROOT_ADC][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ADC][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ADC][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ADC][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_BUS_AON][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUS_AON][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUS_AON][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUS_AON][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_GLITCHFILTER][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_GLITCHFILTER][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_GLITCHFILTER][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_GLITCHFILTER][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_GPT1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_GPT1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_GPT1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_GPT1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_I3C1_SLOW][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_I3C1_SLOW][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_I3C1_SLOW][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_I3C1_SLOW][3] = CLOCK_SRC_OSC24M,

    [CLOCK_ROOT_LPI2C1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPTMR1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPTMR1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPTMR1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPTMR1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART1][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART2][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_M33][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M33][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_M33][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_M33][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_M33_SYSTICK][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M33_SYSTICK][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_M33_SYSTICK][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_M33_SYSTICK][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_PDM][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_PDM][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_PDM][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_PDM][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SAI1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI1][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI1][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI1][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_TPM2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TPM2][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_TPM2][2] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_TPM2][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_A55][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_A55][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_A55][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_A55][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_A55_MTR_BUS][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_A55_MTR_BUS][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_A55_MTR_BUS][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_A55_MTR_BUS][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_A55_PERIPH][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_A55_PERIPH][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_A55_PERIPH][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_A55_PERIPH][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_DRAM_ALT][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DRAM_ALT][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_DRAM_ALT][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_DRAM_ALT][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_DRAM_APB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DRAM_APB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_DRAM_APB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_DRAM_APB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_DISP_APB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISP_APB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_DISP_APB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_DISP_APB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_DISP_AXI][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISP_AXI][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_DISP_AXI][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_DISP_AXI][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_DISP_PIX][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISP_PIX][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_DISP_PIX][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_DISP_PIX][3] = CLOCK_SRC_SYSPLL1_PFD0,

    [CLOCK_ROOT_HSIO_ACSCAN_480M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO_ACSCAN_480M][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_HSIO_ACSCAN_480M][2] = CLOCK_SRC_ENCODER_PFD1,
    [CLOCK_ROOT_HSIO_ACSCAN_480M][3] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,

    [CLOCK_ROOT_HSIO_ACSCAN_80M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO_ACSCAN_80M][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HSIO_ACSCAN_80M][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HSIO_ACSCAN_80M][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_HSIO][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIO][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIO][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIO_PCIE_AUX][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO_PCIE_AUX][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HSIO_PCIE_AUX][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HSIO_PCIE_AUX][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_HSIO_PCIE_TEST_160M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO_PCIE_TEST_160M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIO_PCIE_TEST_160M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIO_PCIE_TEST_160M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIO_PCIE_TEST_400M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO_PCIE_TEST_400M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIO_PCIE_TEST_400M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIO_PCIE_TEST_400M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIO_PCIE_TEST_500M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO_PCIE_TEST_500M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIO_PCIE_TEST_500M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIO_PCIE_TEST_500M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIO_PCIE_TEST_50M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO_PCIE_TEST_50M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIO_PCIE_TEST_50M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIO_PCIE_TEST_50M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIO_USB_TEST_60M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO_USB_TEST_60M][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HSIO_USB_TEST_60M][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HSIO_USB_TEST_60M][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_BUS_M7_0][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUS_M7_0][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUS_M7_0][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUS_M7_0][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_M7_0][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M7_0][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_M7_0][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_M7_0][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_M7_0_SYSTICK][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M7_0_SYSTICK][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_M7_0_SYSTICK][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_M7_0_SYSTICK][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_BUS_M7_1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUS_M7_1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUS_M7_1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUS_M7_1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_M7_1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M7_1][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_M7_1][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_M7_1][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_M7_1_SYSTICK][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M7_1_SYSTICK][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_M7_1_SYSTICK][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_M7_1_SYSTICK][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_BUS_NETCMIX][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUS_NETCMIX][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUS_NETCMIX][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUS_NETCMIX][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ECAT][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ECAT][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ECAT][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ECAT][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENET][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENET][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_ENET][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_ENET_PHY_TEST_200M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET_PHY_TEST_200M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENET_PHY_TEST_200M][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENET_PHY_TEST_200M][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENET_PHY_TEST_500M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET_PHY_TEST_500M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENET_PHY_TEST_500M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_ENET_PHY_TEST_500M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_ENET_PHY_TEST_667M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET_PHY_TEST_667M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENET_PHY_TEST_667M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_ENET_PHY_TEST_667M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_ENET_REF][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET_REF][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENET_REF][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENET_REF][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENET_TIMER1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET_TIMER1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ENET_TIMER1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENET_TIMER1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENET_TIMER2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET_TIMER2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ENET_TIMER2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENET_TIMER2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENET_TIMER3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET_TIMER3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ENET_TIMER3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENET_TIMER3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_FLEXIO3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_FLEXIO3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_FLEXIO3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_FLEXIO3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_FLEXIO4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_FLEXIO4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_FLEXIO4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_FLEXIO4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_M33_SYNC][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M33_SYNC][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_M33_SYNC][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_M33_SYNC][3] = CLOCK_SRC_ENCODER_PFD0,

    [CLOCK_ROOT_M33_SYNC_SYSTICK][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M33_SYNC_SYSTICK][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_M33_SYNC_SYSTICK][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_M33_SYNC_SYSTICK][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_MAC0][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MAC0][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_MAC0][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_MAC0][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_MAC1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MAC1][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_MAC1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_MAC1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_MAC2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MAC2][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_MAC2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_MAC2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_MAC3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MAC3][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_MAC3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_MAC3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_MAC4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MAC4][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_MAC4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_MAC4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_MAC5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MAC5][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_MAC5][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_MAC5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_NOC_APB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_NOC_APB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_NOC_APB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_NOC_APB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_NOC][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_NOC][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_NOC][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_NOC][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_NPU_APB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_NPU_APB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_NPU_APB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_NPU_APB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_NPU][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_NPU][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_NPU][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_NPU][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_CCM_CKO1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CCM_CKO1][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CCM_CKO1][2] = CLOCK_SRC_OSC32K,
    [CLOCK_ROOT_CCM_CKO1][3] = CLOCK_SRC_AUDIOPLL1,

    [CLOCK_ROOT_CCM_CKO2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CCM_CKO2][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CCM_CKO2][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_CCM_CKO2][3] = CLOCK_SRC_AUDIOPLL2,

    [CLOCK_ROOT_CCM_CKO3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CCM_CKO3][1] = CLOCK_SRC_OSC32K,
    [CLOCK_ROOT_CCM_CKO3][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_CCM_CKO3][3] = CLOCK_SRC_ENCODER_PFD0,

    [CLOCK_ROOT_CCM_CKO4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CCM_CKO4][1] = CLOCK_SRC_ENCODER_PFD1,
    [CLOCK_ROOT_CCM_CKO4][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_CCM_CKO4][3] = CLOCK_SRC_AUDIOPLL2,

    [CLOCK_ROOT_BISS][0] = CLOCK_SRC_OSC24M, 
    [CLOCK_ROOT_BISS][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2, 
    [CLOCK_ROOT_BISS][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2, 
    [CLOCK_ROOT_BISS][3] = CLOCK_SRC_FRO, 

    [CLOCK_ROOT_BUS_WAKEUP][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUS_WAKEUP][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUS_WAKEUP][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUS_WAKEUP][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN5][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN5][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENDAT2_1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENDAT2_1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ENDAT2_1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENDAT2_1][3] = CLOCK_SRC_ENCODER_PFD1,

    [CLOCK_ROOT_ENDAT2_2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENDAT2_2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ENDAT2_2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENDAT2_2][3] = CLOCK_SRC_ENCODER_PFD1,

    [CLOCK_ROOT_ENDAT3_1_FAST][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENDAT3_1_FAST][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ENDAT3_1_FAST][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENDAT3_1_FAST][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENDAT3_1_SLOW][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENDAT3_1_SLOW][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ENDAT3_1_SLOW][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENDAT3_1_SLOW][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_FLEXIO1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_FLEXIO1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_FLEXIO1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_FLEXIO1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_FLEXIO2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_FLEXIO2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_FLEXIO2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_FLEXIO2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_GPT2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_GPT2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_GPT2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_GPT2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_GPT3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_GPT3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_GPT3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_GPT3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_GPT4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_GPT4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_GPT4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_GPT4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_HIPERFACE1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HIPERFACE1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HIPERFACE1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HIPERFACE1][3] = CLOCK_SRC_ENCODER_PFD0,

    [CLOCK_ROOT_HIPERFACE1_SYNC][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HIPERFACE1_SYNC][1] = CLOCK_SRC_OSC32K,
    [CLOCK_ROOT_HIPERFACE1_SYNC][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HIPERFACE1_SYNC][3] = CLOCK_SRC_ENCODER_PFD0,

    [CLOCK_ROOT_HIPERFACE2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HIPERFACE2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HIPERFACE2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HIPERFACE2][3] = CLOCK_SRC_ENCODER_PFD0,

    [CLOCK_ROOT_HIPERFACE2_SYNC][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HIPERFACE2_SYNC][1] = CLOCK_SRC_OSC32K,
    [CLOCK_ROOT_HIPERFACE2_SYNC][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HIPERFACE2_SYNC][3] = CLOCK_SRC_ENCODER_PFD0,

    [CLOCK_ROOT_I3C2_SLOW][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_I3C2_SLOW][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_I3C2_SLOW][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_I3C2_SLOW][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C5][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C5][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C6][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C6][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C6][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C6][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C7][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C7][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C7][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C7][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C8][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C8][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C8][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C8][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI5][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI5][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI6][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI6][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI6][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI6][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI7][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI7][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI7][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI7][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI8][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI8][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI8][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI8][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPTMR2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPTMR2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPTMR2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPTMR2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART10][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART10][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART10][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART10][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART11][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART11][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART11][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART11][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART12][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART12][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART12][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART12][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART3][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART4][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART5][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART5][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART6][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART6][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART6][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART6][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART7][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART7][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART7][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART7][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART8][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART8][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART8][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART8][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART9][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART9][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART9][2] = CLOCK_SRC_ENCODER_PFD0,
    [CLOCK_ROOT_LPUART9][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_SAI2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI2][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI2][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI2][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SAI3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI3][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI3][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI3][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SAI4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI4][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI4][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI4][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SWO_TRACE][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SWO_TRACE][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_SWO_TRACE][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_SWO_TRACE][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_TPM4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TPM4][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_TPM4][2] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_TPM4][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_TPM5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TPM5][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_TPM5][2] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_TPM5][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_TPM6][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TPM6][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_TPM6][2] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_TPM6][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_USB_PHY_BURUNIN][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_USB_PHY_BURUNIN][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_USB_PHY_BURUNIN][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_USB_PHY_BURUNIN][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_USDHC1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_USDHC1][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_USDHC1][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_USDHC1][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_USDHC2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_USDHC2][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_USDHC2][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_USDHC2][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_USDHC3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_USDHC3][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_USDHC3][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_USDHC3][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_V2X_PK][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_V2X_PK][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_V2X_PK][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_V2X_PK][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_WAKEUP_AXI][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_WAKEUP_AXI][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_WAKEUP_AXI][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_WAKEUP_AXI][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_XSPI_SLV_ROOT][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_XSPI_SLV_ROOT][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_XSPI_SLV_ROOT][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_XSPI_SLV_ROOT][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_XSPI1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_XSPI1][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_XSPI1][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_XSPI1][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_XSPI2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_XSPI2][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_XSPI2][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_XSPI2][3] = CLOCK_SRC_SYSPLL1_PFD2,
};

/* CCM GPR-selected clocks may be sources/roots.  Encode selections
 * that map to roots as offset from CLOCK_NUM_SRC for unique mapping.
 */
const ccm_gpr_sel_attr_t g_clockGprSel[CLOCK_NUM_GPR_SEL] =
{
    [CLOCK_GPR_SEL_EXT]
    {
        .selIdx = 0U,
        .selMask = 0x1U,
        .selShift = 0U,
        .selMux[0] = CLOCK_SRC_EXT1,
        .selMux[1] = CLOCK_SRC_EXT2,
    },
    /* EXT2/EXT3/EXT4 all tied to GND */

    [CLOCK_GPR_SEL_A55C0]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE0_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE0_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD0,
    },

    [CLOCK_GPR_SEL_A55C1]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE1_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE1_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD0,
    },

    [CLOCK_GPR_SEL_A55C2]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE2_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE2_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD1,
    },

    [CLOCK_GPR_SEL_A55C3]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE3_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE3_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD1,
    },

    [CLOCK_GPR_SEL_A55P]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_PLATFORM_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_PLATFORM_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD3,
    },

    [CLOCK_GPR_SEL_DRAM]
    {
        .selIdx = 2U,
        .selMask = CCM_GPR_SHARED2_DRAM_PLL_BYPASS_MASK,
        .selShift = CCM_GPR_SHARED2_DRAM_PLL_BYPASS_SHIFT,
        .selMux[0] = CLOCK_SRC_DRAMPLL,
        .selMux[1] = CLOCK_NUM_SRC + CLOCK_ROOT_DRAM_ALT,
    },

    [CLOCK_GPR_SEL_TEMPSENSE]
    {
        .selIdx = 2U,
        .selMask = CCM_GPR_SHARED2_ANAMIX_TEMPSENSE_CLK_SEL_MASK,
        .selShift = CCM_GPR_SHARED2_ANAMIX_TEMPSENSE_CLK_SEL_SHIFT,
        .selMux[0] = CLOCK_SRC_OSC24M,
        .selMux[1] = CLOCK_SRC_FRO,
    }
};

/*--------------------------------------------------------------------------*/
/* Check if CCM clock source power domain enabled                           */
/*--------------------------------------------------------------------------*/
static bool CLOCK_SourcePdIsOn(uint32_t sourceIdx)
{
    bool pdOn = true;

    switch(sourceIdx)
    {
        case CLOCK_SRC_ARMPLL_VCO:
        case CLOCK_SRC_ARMPLL_PFD0:
        case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
        case CLOCK_SRC_ARMPLL_PFD1:
        case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
        case CLOCK_SRC_ARMPLL_PFD2:
        case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
        case CLOCK_SRC_ARMPLL_PFD3:
        case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
            pdOn = SRC_MixIsPwrReady(PWR_MIX_SLICE_IDX_A55P);
            break;

        case CLOCK_SRC_DRAMPLL_VCO:
        case CLOCK_SRC_DRAMPLL:
            pdOn = SRC_MixIsPwrReady(PWR_MIX_SLICE_IDX_DDR);
            break;

        case CLOCK_SRC_HSIOPLL_VCO:
        case CLOCK_SRC_HSIOPLL:
              /* TODO */
            pdOn = SRC_MixIsPwrReady(PWR_MIX_SLICE_IDX_HSIO_TOP);
            break;

        case CLOCK_SRC_LDBPLL_VCO:
        case CLOCK_SRC_LDBPLL:
              /* TODO */
            pdOn = SRC_MixIsPwrReady(PWR_MIX_SLICE_IDX_DISPLAY);
            break;

        default:
            ; /* Intentional empty default */
            break;
    }

    return pdOn;
}

/*--------------------------------------------------------------------------*/
/* Get CCM clock source enable status                                       */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceGetEnable(uint32_t sourceIdx)
{
    bool clkEnable = false;
    
    if (CLOCK_SourcePdIsOn(sourceIdx))
    {
        switch(sourceIdx)
        {
            case CLOCK_SRC_EXT:
                clkEnable = true;
                break;

            case CLOCK_SRC_OSC32K:
                clkEnable = true;
                break;

            case CLOCK_SRC_OSC24M:
                clkEnable = true;
                break;

            case CLOCK_SRC_FRO:
                clkEnable = true;
                break;

            case CLOCK_SRC_SYSPLL1_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_SYS1,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_DIV2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;
            
            case CLOCK_SRC_SYSPLL1_PFD1:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_DIV2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 1,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;
            
            case CLOCK_SRC_SYSPLL1_PFD2_DIV2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK);
                break;

            case CLOCK_SRC_AUDIOPLL1_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_AUDIO1,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_AUDIOPLL1:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_AUDIO1,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_AUDIOPLL2_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_AUDIO2,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_AUDIOPLL2:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_AUDIO2,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_ENCODER_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_ENCODER,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_ENCODER_PFD0_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ENCODER,
                    0, PLL_NO_OF_DFS_ENABLE_MASK);
                break;
            case CLOCK_SRC_ENCODER_PFD0:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ENCODER,
                    0, PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;
            case CLOCK_SRC_ENCODER_PFD1_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ENCODER,
                    1, PLL_NO_OF_DFS_ENABLE_MASK);
                break;
            case CLOCK_SRC_ENCODER_PFD1:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ENCODER,
                    1, PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_ARMPLL_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_ARM,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD0:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD1:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 2U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 2U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 3U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD3:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 3U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_DRAMPLL_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_DRAM,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_DRAMPLL:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_DRAM,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_HSIOPLL_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_HSIO,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_HSIOPLL:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_HSIO,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_LDBPLL_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_LDB,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_LDBPLL:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_LDB,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_EXT1:
                clkEnable = true;
                break;

            default:
                ; /* Intentional empty default */
                break;
        }
    }

    return clkEnable;
}

/*--------------------------------------------------------------------------*/
/* Set CCM clock source enable                                              */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceSetEnable(uint32_t sourceIdx, bool enable)
{
    bool updateEnable = false;

    if (CLOCK_SourcePdIsOn(sourceIdx))
    {
        switch(sourceIdx)
        {
            case CLOCK_SRC_OSC32K:
                updateEnable = true;
                break;

            case CLOCK_SRC_OSC24M:
                updateEnable = true;
                break;

            case CLOCK_SRC_SYSPLL1_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_SYS1,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_DIV2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_DIV2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_DIV2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK, enable);
                break;

            case CLOCK_SRC_AUDIOPLL1_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_AUDIO1,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_AUDIOPLL1:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_AUDIO1,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            case CLOCK_SRC_AUDIOPLL2_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_AUDIO2,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_AUDIOPLL2:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_AUDIO2,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

           case CLOCK_SRC_ENCODER_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_ENCODER,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_ENCODER_PFD0_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ENCODER, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;
            case CLOCK_SRC_ENCODER_PFD0:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ENCODER, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;
            case CLOCK_SRC_ENCODER_PFD1_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ENCODER, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;
            case CLOCK_SRC_ENCODER_PFD1:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ENCODER, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_ARM,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD0:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD1:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 2U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 2U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 3U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD3:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 3U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_DRAMPLL_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_DRAM,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_DRAMPLL:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_DRAM,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            case CLOCK_SRC_HSIOPLL_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_HSIO,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_HSIOPLL:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_HSIO,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            case CLOCK_SRC_LDBPLL_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_LDB,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_LDBPLL:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_LDB,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            default:
                ; /* Intentional empty default */
                break;
        }
    }

    return updateEnable;
}

/*--------------------------------------------------------------------------*/
/* Get CCM clock source rate                                                */
/*--------------------------------------------------------------------------*/
uint64_t CLOCK_SourceGetRate(uint32_t sourceIdx)
{
    uint64_t rate = 0UL;

    if (CLOCK_SourcePdIsOn(sourceIdx))
    {        
        switch(sourceIdx)
        {
            case CLOCK_SRC_EXT:
                /* Refrain from calling CLOCK_GprSelGetRate to avoid possible recursion */
                rate = CCM_GprSelExtGetRate();
                break;

            case CLOCK_SRC_OSC32K:
                rate = CLOCK_OSC32K_HZ;
                break;

            case CLOCK_SRC_OSC24M:
                rate = CLOCK_OSC24M_HZ;
                break;

            case CLOCK_SRC_FRO:
                rate = CLOCK_FRO_HZ;
                break;

            case CLOCK_SRC_SYSPLL1_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_SYS1, true);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_UNGATED:
            case CLOCK_SRC_SYSPLL1_PFD0:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 0U, false);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_DIV2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 0U, true);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_UNGATED:
            case CLOCK_SRC_SYSPLL1_PFD1:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 1U, false);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_DIV2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 1U, true);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_UNGATED:
            case CLOCK_SRC_SYSPLL1_PFD2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 2U, false);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_DIV2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 2U, true);
                break;

            case CLOCK_SRC_AUDIOPLL1_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_AUDIO1, true);
                break;

            case CLOCK_SRC_AUDIOPLL1:
                rate = FRACTPLL_GetRate(CLOCK_PLL_AUDIO1, false);
                break;

            case CLOCK_SRC_AUDIOPLL2_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_AUDIO2, true);
                break;

            case CLOCK_SRC_AUDIOPLL2:
                rate = FRACTPLL_GetRate(CLOCK_PLL_AUDIO2, false);
                break;

            case CLOCK_SRC_ENCODER_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_ENCODER, true);
                break;

            case CLOCK_SRC_ENCODER_PFD0_UNGATED:
            case CLOCK_SRC_ENCODER_PFD0:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ENCODER, 0, false);
                break;

            case CLOCK_SRC_ENCODER_PFD1_UNGATED:
            case CLOCK_SRC_ENCODER_PFD1:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ENCODER, 1, false);
                break;

            case CLOCK_SRC_ARMPLL_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_ARM, true);
                break;

            case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
            case CLOCK_SRC_ARMPLL_PFD0:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ARM, 0U, false);
                break;

            case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
            case CLOCK_SRC_ARMPLL_PFD1:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ARM, 1U, false);
                break;

            case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
            case CLOCK_SRC_ARMPLL_PFD2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ARM, 2U, false);
                break;

            case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
            case CLOCK_SRC_ARMPLL_PFD3:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ARM, 3U, false);
                break;

            case CLOCK_SRC_DRAMPLL_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_DRAM, true);
                break;

            case CLOCK_SRC_DRAMPLL:
                rate = FRACTPLL_GetRate(CLOCK_PLL_DRAM, false);
                break;

            case CLOCK_SRC_HSIOPLL_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_HSIO, true);
                break;

            case CLOCK_SRC_HSIOPLL:
                rate = FRACTPLL_GetRate(CLOCK_PLL_HSIO, false);
                break;

            case CLOCK_SRC_LDBPLL_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_LDB, true);
                break;

            case CLOCK_SRC_LDBPLL:
                rate = FRACTPLL_GetRate(CLOCK_PLL_LDB, false);
                break;

            case CLOCK_SRC_EXT1:
                /* EXT1 is board-specific.  Return rate stored on
                 * previous set rate call for this source.
                 */
                rate = g_clockExt1Rate;
                break;

                /* EXT2 internally tied to GND, no case needed */

            default:
                ; /* Intentional empty default */
                break;
        }
    }

    return rate;
}

/*--------------------------------------------------------------------------*/
/* Set CCM clock source rate                                                */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceSetRate(uint32_t sourceIdx, uint64_t rate,
    uint32_t roundRule)
{
    bool updateRate = false;

    if (CLOCK_SourcePdIsOn(sourceIdx))
    {
        switch(sourceIdx)
        {
            case CLOCK_SRC_SYSPLL1_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_SYS1, true, rate);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_SYS1, 0U, rate);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_SYS1, 1U, rate);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_SYS1, 2U, rate);
                break;

            case CLOCK_SRC_AUDIOPLL1_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_AUDIO1, true, rate);
                break;

            case CLOCK_SRC_AUDIOPLL1:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_AUDIO1, false, rate);
                break;

            case CLOCK_SRC_AUDIOPLL2_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_AUDIO2, true, rate);
                break;

            case CLOCK_SRC_AUDIOPLL2:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_AUDIO2, false, rate);
                break;

            case CLOCK_SRC_ENCODER_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_ENCODER, true, rate);
                break;

            case CLOCK_SRC_ENCODER_PFD0_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ENCODER, 0U, rate);
                break;

            case CLOCK_SRC_ENCODER_PFD1_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ENCODER, 1U, rate);
                break;

            case CLOCK_SRC_ARMPLL_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_ARM, true, rate);
                break;

            case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ARM, 0U, rate);
                break;

            case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ARM, 1U, rate);
                break;

            case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ARM, 2U, rate);
                break;

            case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ARM, 3U, rate);
                break;

            case CLOCK_SRC_DRAMPLL_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_DRAM, true, rate);
                break;

            case CLOCK_SRC_DRAMPLL:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_DRAM, false, rate);
                break;

            case CLOCK_SRC_EXT1:
                /* EXT1 is board-specific.  Store the rate to be
                 * used on subsequent get rate calls for this source.
                 */
                g_clockExt1Rate = rate;
                updateRate = true;
                break;

            default:
                ; /* Intentional empty default */
                break;
        }
    }

    return updateRate;
}

/*--------------------------------------------------------------------------*/
/* Set CCM clock source spread spectrum                                     */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceSetSsc(uint32_t sourceIdx, uint32_t spreadPercent,
    uint32_t modFreq, uint32_t enable)
{
    bool setSscConfig = false;

    switch (sourceIdx)
    {
        case CLOCK_SRC_SYSPLL1_VCO:
            /* PLL SYS */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_SYS1, spreadPercent,
                modFreq, enable);
            break;

        case CLOCK_SRC_AUDIOPLL1_VCO:
            /* PLL AUDIO1 */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_AUDIO1,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_AUDIOPLL2_VCO:
            /* PLL AUDIO2 */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_AUDIO2,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_DRAMPLL_VCO:
            /* PLL DRAM */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_DRAM,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_HSIOPLL_VCO:
            /* PLL HSIO */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_HSIO,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_LDBPLL_VCO:
            /* PLL LDB */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_LDB,
                spreadPercent, modFreq, enable);
            break;

        default:
            ; /* Intentional empty default */
            break;
    }

    return setSscConfig;
}

/*--------------------------------------------------------------------------*/
/* Get CCM clock source spread spectrum                                     */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceGetSsc(uint32_t sourceIdx, uint32_t *spreadPercent,
    uint32_t *modFreq, uint32_t *enable)
{
    bool getSscConfig = false;

    switch (sourceIdx)
    {
        case CLOCK_SRC_SYSPLL1_VCO:
            /* PLL SYS */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_SYS1, spreadPercent,
                modFreq, enable);
            break;

        case CLOCK_SRC_AUDIOPLL1_VCO:
            /* PLL AUDIO1 */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_AUDIO1,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_AUDIOPLL2_VCO:
            /* PLL AUDIO2 */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_AUDIO2,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_DRAMPLL_VCO:
            /* PLL DRAM */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_DRAM,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_HSIOPLL_VCO:
            /* PLL HSIO */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_HSIO,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_LDBPLL_VCO:
            /* PLL LDB */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_LDB,
                spreadPercent, modFreq, enable);
            break;

        default:
            ; /* Intentional empty default */
            break;
    }

    return getSscConfig;
}

