/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright 2019, 2023 NXP
 */

/*This file is generated by script, dont change it mannually*/

#ifndef ROM_SOC_MEMORY_MAP_H
#define ROM_SOC_MEMORY_MAP_H

#define ROM_NS_BASE                 ((uint32_t)0x00000000)
#define ROM_NS_SIZE                 ((uint32_t)0x30000)
#define ROM_NS_END                  (ROM_NS_BASE + ROM_NS_SIZE - 1U)

#define ROM_BASE                    (0x10000000U)
#define ROM_SIZE                    (0x18000U)
#define ROM_END                     (ROM_BASE + ROM_SIZE - 1U)

#define FLEXSPI0_MEMORY_SIZE        ((uint32_t)0x08000000)

#define FLEXSPI0_MEMORY_NS_BASE     ((uint32_t)0x28000000)

#define FLEXSPI0_MEMORY_S_BASE      ((uint32_t)0x38000000)

#define FLEXSPI0_MEMORY_NS_END      (FLEXSPI0_MEMORY_NS_BASE + \
                                     FLEXSPI0_MEMORY_SIZE - (uint32_t)1)
#define FLEXSPI0_MEMORY_END         (FLEXSPI0_MEMORY_S_BASE + \
                                     FLEXSPI0_MEMORY_SIZE - (uint32_t)1)
#define OCRAM_SIZE                  (0x58000UL)
#define OCRAM_NS_BASE               (((uint32_t)0x20480000))
#define OCRAM_NS_END                (OCRAM_NS_BASE + OCRAM_SIZE - (uint32_t)1)
#define OCRAM_BASE                  (0x30480000UL)
#define OCRAM_END                   (OCRAM_BASE + OCRAM_SIZE - (uint32_t)1)

#define DDRMIX_BLK_CTRL_NS_BASE     ((uint32_t)0x4E010000)
#define DDRMIX_BLK_CTRL_BASE        ((uint32_t)0x5E010000)
#define DDRC_NS_BASE                ((uint32_t)0x4E080000)
#define DDRC_BASE                   ((uint32_t)0x5E080000)
#define DDRPHY_NS_BASE              ((uint32_t)0x4E800000)
#define DDRPHY_BASE                 ((uint32_t)0x5E800000)

#define SENTINEL_NS_BASE            ((uint32_t)0x47500000)
#define SENTINEL_BASE               ((uint32_t)0x57500000)

#define USB0_NS_RBASE               ((uint32_t)0x4C100000)
#define USB0_RBASE                  ((uint32_t)0x5C100000)

#define MECC_NS_RBASE               ((uint32_t)0x490A0000)
#define MECC_RBASE                  ((uint32_t)0x590A0000)

/* USB port 1, 3.0, DWC3, for phy init use */
#define USB1PHY_BASE_ADDR           ((uint32_t)0x5C1F0000)
#define USB1PHY_NS_BASE_ADDR        ((uint32_t)0x4C1F0000)

#define USB0_PHY_NS_RBASE           ((uint32_t)0x4C180000)
#define USB0_PHY_RBASE              ((uint32_t)0x5C180000)

#define USB1_NS_RBASE               ((uint32_t)0x4C200000)
#define USB1_RBASE                  ((uint32_t)0x5C200000)

#define USB1_PHY_NS_RBASE           ((uint32_t)0x4C280000)
#define USB1_PHY_RBASE              ((uint32_t)0x5C280000)

#define BLK_CTRL_S_AONMIX_RBASE     ((uint32_t)0x544F0000)

#define AIPS_IPS_SLOT_SIZE          ((uint32_t)0x10000)
#define AIPS1_IPS_NS_BASE_ADDR      ((uint32_t)0x44000000)
#define AIPS1_IPS_BASE_ADDR         ((uint32_t)0x54000000)

#define APIS1_IPS_NS_SLOT_ADDR(x)   (AIPS1_IPS_NS_BASE_ADDR + \
                                     (x) * AIPS_IPS_SLOT_SIZE)
#define APIS1_IPS_SLOT_ADDR(x)      (AIPS1_IPS_BASE_ADDR + \
                                     (x) * AIPS_IPS_SLOT_SIZE)

#define AONMIX_BLK_CTL_NS_NS_RBASE  APIS1_IPS_NS_SLOT_ADDR(((uint32_t)33))
#define AONMIX_BLK_CTL_NS_RBASE     APIS1_IPS_SLOT_ADDR(((uint32_t)33))

#define SYSCTRL_CTL_NS_RBASE        APIS1_IPS_NS_SLOT_ADDR(((uint32_t)41))
#define SYSCTRL_CTL_RBASE           APIS1_IPS_SLOT_ADDR(((uint32_t)41))

#define SYSCTRL_CMP_NS_RBASE        APIS1_IPS_NS_SLOT_ADDR(((uint32_t)42))
#define SYSCTRL_CMP_RBASE           APIS1_IPS_SLOT_ADDR(((uint32_t)42))

#define SYSCTRL_RD_NS_RBASE         APIS1_IPS_NS_SLOT_ADDR(((uint32_t)43))
#define SYSCTRL_RD_RBASE            APIS1_IPS_SLOT_ADDR(((uint32_t)43))

#define TSTMR1_NS_RBASE             APIS1_IPS_NS_SLOT_ADDR(((uint32_t)44))
#define TSTMR1_RBASE                APIS1_IPS_SLOT_ADDR(((uint32_t)44))

#define LPWDOG1_NS_RBASE            APIS1_IPS_NS_SLOT_ADDR(((uint32_t)45))
#define LPWDOG1_RBASE               APIS1_IPS_SLOT_ADDR(((uint32_t)45))

#define LPSPI1_NS_RBASE             APIS1_IPS_NS_SLOT_ADDR(((uint32_t)54))
#define LPSPI1_RBASE                APIS1_IPS_SLOT_ADDR(((uint32_t)54))

#define LPSPI2_NS_RBASE             APIS1_IPS_NS_SLOT_ADDR(((uint32_t)55))
#define LPSPI2_RBASE                APIS1_IPS_SLOT_ADDR(((uint32_t)55))

#define LPUART1_NS_RBASE            APIS1_IPS_NS_SLOT_ADDR(((uint32_t)56))
#define LPUART1_RBASE               APIS1_IPS_SLOT_ADDR(((uint32_t)56))

#define LPUART2_NS_RBASE            APIS1_IPS_NS_SLOT_ADDR(((uint32_t)57))
#define LPUART2_RBASE               APIS1_IPS_SLOT_ADDR(((uint32_t)57))

#define IOMUXC_NS_RBASE             APIS1_IPS_NS_SLOT_ADDR(((uint32_t)60))
#define IOMUXC_RBASE                APIS1_IPS_SLOT_ADDR(((uint32_t)60))

#define IOMUXC_GPR_NS_RBASE         APIS1_IPS_NS_SLOT_ADDR(((uint32_t)61))
#define IOMUXC_GPR_RBASE            APIS1_IPS_SLOT_ADDR(((uint32_t)61))

#define ROMCP1_NS_RBASE             APIS1_IPS_NS_SLOT_ADDR(((uint32_t)67))
#define ROMCP1_RBASE                APIS1_IPS_SLOT_ADDR(((uint32_t)67))

#define CCM_NS_RBASE                APIS1_IPS_NS_SLOT_ADDR(((uint32_t)69))
#define CCM_RBASE                   APIS1_IPS_SLOT_ADDR(((uint32_t)69))

#define SRC_NS_RBASE                APIS1_IPS_NS_SLOT_ADDR(((uint32_t)70))
#define SRC_RBASE                   APIS1_IPS_SLOT_ADDR(((uint32_t)70))

#define ANATOP_NS_RBASE             APIS1_IPS_NS_SLOT_ADDR(((uint32_t)72))
#define ANATOP_RBASE                APIS1_IPS_SLOT_ADDR(((uint32_t)72))

#define AIPS2_IPS_NS_BASE_ADDR      (((uint32_t)0x42000000))
#define AIPS2_IPS_BASE_ADDR         (((uint32_t)0x52000000))

#define APIS2_IPS_NS_SLOT_ADDR(x)   (AIPS2_IPS_NS_BASE_ADDR + \
                                     (x) * AIPS_IPS_SLOT_SIZE)
#define APIS2_IPS_SLOT_ADDR(x)      (AIPS2_IPS_BASE_ADDR + \
                                     (x) * AIPS_IPS_SLOT_SIZE)

#define TSTMR2_NS_RBASE             APIS2_IPS_NS_SLOT_ADDR(((uint32_t)72))
#define TSTMR2_RBASE                APIS2_IPS_SLOT_ADDR(((uint32_t)72))

#define LPWDOG3_NS_RBASE            APIS2_IPS_NS_SLOT_ADDR(((uint32_t)73))
#define LPWDOG3_RBASE               APIS2_IPS_SLOT_ADDR(((uint32_t)73))

#define LPSPI3_NS_RBASE             APIS2_IPS_NS_SLOT_ADDR(((uint32_t)85))
#define LPSPI3_RBASE                APIS2_IPS_SLOT_ADDR(((uint32_t)85))

#define LPSPI4_NS_RBASE             APIS2_IPS_NS_SLOT_ADDR(((uint32_t)86))
#define LPSPI4_RBASE                APIS2_IPS_SLOT_ADDR(((uint32_t)86))

#define LPUART3_NS_RBASE            APIS2_IPS_NS_SLOT_ADDR(((uint32_t)87))
#define LPUART3_RBASE               APIS2_IPS_SLOT_ADDR(((uint32_t)87))

#define FLEXSPI1_NS_RBASE           APIS2_IPS_NS_SLOT_ADDR(((uint32_t)94))
#define FLEXSPI1_RBASE              APIS2_IPS_SLOT_ADDR(((uint32_t)94))

#define ROMCP2_NS_RBASE             APIS2_IPS_NS_SLOT_ADDR(((uint32_t)100))
#define ROMCP2_RBASE                APIS2_IPS_SLOT_ADDR(((uint32_t)100))

#define LPSPI5_NS_RBASE             APIS2_IPS_NS_SLOT_ADDR(((uint32_t)111))
#define LPSPI5_RBASE                APIS2_IPS_SLOT_ADDR(((uint32_t)111))

#define LPSPI6_NS_RBASE             APIS2_IPS_NS_SLOT_ADDR(((uint32_t)112))
#define LPSPI6_RBASE                APIS2_IPS_SLOT_ADDR(((uint32_t)112))

#define LPSPI7_NS_RBASE             APIS2_IPS_NS_SLOT_ADDR(((uint32_t)113))
#define LPSPI7_RBASE                APIS2_IPS_SLOT_ADDR(((uint32_t)113))

#define LPSPI8_NS_RBASE             APIS2_IPS_NS_SLOT_ADDR(((uint32_t)114))
#define LPSPI8_RBASE                APIS2_IPS_SLOT_ADDR(((uint32_t)114))

#define AIPS3_IPS_NS_BASE_ADDR      (((uint32_t)0x42800000))
#define AIPS3_IPS_BASE_ADDR         (((uint32_t)0x52800000))

#define APIS3_IPS_NS_SLOT_ADDR(x)   (AIPS3_IPS_NS_BASE_ADDR + \
                                     (x) * AIPS_IPS_SLOT_SIZE)
#define APIS3_IPS_SLOT_ADDR(x)      (AIPS3_IPS_BASE_ADDR + \
                                     (x) * AIPS_IPS_SLOT_SIZE)

#define USDHC1_NS_RBASE             APIS3_IPS_NS_SLOT_ADDR(((uint32_t)5))
#define USDHC1_RBASE                APIS3_IPS_SLOT_ADDR(((uint32_t)5))

#define USDHC2_NS_RBASE             APIS3_IPS_NS_SLOT_ADDR(((uint32_t)6))
#define USDHC2_RBASE                APIS3_IPS_SLOT_ADDR(((uint32_t)6))

#define USDHC3_NS_RBASE             APIS3_IPS_NS_SLOT_ADDR(((uint32_t)11))
#define USDHC3_RBASE                APIS3_IPS_SLOT_ADDR(((uint32_t)11))

#define GPIO1_NS_RBASE               (((uint32_t)0x47400000))
#define GPIO2_NS_RBASE               (((uint32_t)0x43810000))
#define GPIO3_NS_RBASE               (((uint32_t)0x43820000))
#define GPIO4_NS_RBASE               (((uint32_t)0x43840000))
#define GPIO5_NS_RBASE               (((uint32_t)0x43850000))

#define GPIO1_RBASE                 (((uint32_t)0x57400000))
#define GPIO2_RBASE                 (((uint32_t)0x53810000))
#define GPIO3_RBASE                 (((uint32_t)0x53820000))
#define GPIO4_RBASE                 (((uint32_t)0x53840000))
#define GPIO5_RBASE                 (((uint32_t)0x53850000))

#define CSTCU_BASE                  ((uint32_t)0x54590000)
#define LSTCU_AON_BASE              ((uint32_t)0x545A0000)
#define LSTCU_NOC_BASE              ((uint32_t)0x590B0000)

#define CM33CC_RBASE                ((uint32_t)0x54400000)

#define NPU_SRAM_NS_BASE        (0x4AA00000U)
#define NPU_SRAM_NS_SIZE        (0x100000U)
#define NPU_SRAM_NS_END         (NPU_SRAM_NS_BASE - 1U + NPU_SRAM_NS_SIZE)

#define NPU_SRAM_BASE           (0x5AA00000U)
#define NPU_SRAM_SIZE           (0x100000U)
#define NPU_SRAM_END            (NPU_SRAM_BASE - 1U + NPU_SRAM_SIZE)

#define MMU_TBL_BASE            (0x20482000U)

#define NOC_MECC_BASE_NS        (0x490A0000U)
#define NOC_MECC_BASE           (0x590A0000U)
#endif /*_SOC_MEMORY_MAP_H_*/

